sudo: required
dist: trusty
language: node_js
node_js:
  - '8.9.4'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli
#- npm install -g karma
#- npm install -g codecov
#- npm install -g sw-precache
- npm install
- ng b -c=ci

after_success:
#- npm run prep
#- npm run precache
#- codecov

script:
#- ng test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
target_branch: gh-pages